name: web-deploy

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Deploy react app to github pages
              run: |
                  pwd
                  cd web
                  pwd
                  npm ci
                  CI=false npm run build
                  git config user.name github-actions
                  git config user.email github-actions@github.com
                  git --work-tree build add --all
                  git commit -m "Auto deployment"
                  git push origin HEAD:gh-pages --force
